export const ROLES = {
  USER: 'user',
  SELLER: 'seller',
  ADMIN: 'admin',
};

export const PERMISSIONS = {
  MANAGE_CATALOG: [ROLES.ADMIN, ROLES.SELLER],
  VIEW_ANALYTICS: [ROLES.ADMIN, ROLES.SELLER],
  MANAGE_USERS: [ROLES.ADMIN],
  PLACE_ORDER: [ROLES.USER, ROLES.SELLER, ROLES.ADMIN],
};

export default ROLES;
