export const ROUTES = {
  HOME: '/',
  CATEGORY: '/category/:id',
  PRODUCT_DETAIL: '/product/:id',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PC_BUILDER: '/pc-builder',
  COMPARISON: '/comparison',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  DASHBOARD_ORDERS: '/dashboard?tab=orders',
  DASHBOARD_WISHLIST: '/dashboard?tab=wishlist',
  DASHBOARD_PROFILE: '/dashboard?tab=profile',
  SELLER_DASHBOARD: '/seller/dashboard',
  SELLER_PRODUCTS: '/seller/products',
  SELLER_ORDERS: '/seller/orders',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_ORDERS: '/admin/orders',
  NOT_FOUND: '*',
};

export default ROUTES;
